server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:creditdb
    driver-class-name: org.h2.Driver
    username: admin
    password: admin

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  security:
    user:
      name: admin
      password: admin
      roles: ADMIN







